1_Installation_Files/includes/templates/IH_INSTALL/jscript/jscript_imagehover.js
=> fix issue with trailimageid loading in head

1_Installation_Files/YOUR_ADMIN/includes/modules/category_product_listing.DEFAULT.php.OLD.IH4, 1_Installation_Files/YOUR_ADMIN/includes/modules/category_product_listing_IH4.php, 1_Installation_Files/includes/modules/IH_INSTALL/additional_images.php, 1_Installation_Files/includes/modules/pages/popup_image_additional/header_php.DEFAULT.php.OLD.IH4, 1_Installation_Files/includes/modules/pages/popup_image_additional/header_php_IH4.php
I've updated the core files to be compatible with Zen Cart 1.5.5 and done some limited testing. ReadMe has *not* been updated at this point. Was waiting on further testing before doing so.
=> Zen Cart 1.5.5 updates

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/functions/extra_functions/functions_bmz_io.php, 1_Installation_Files (v1.5.5)/includes/classes/bmz_gif_info.class.php, 1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, 1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_io.php
Update the class (and a couple of function) files, changing the
class-constructor names to __construct and applying PSR-2 styling.
=> #14: Class constructors for PHP 7+

1_Installation_Files (v1.5.5)/includes/modules/YOUR_TEMPLATE/additional_images.php, 1_Installation_Files (v1.5.5)/includes/modules/YOUR_TEMPLATE/main_product_image.php
Initialize the change with the files to be modified, using ZC1.5.5e as
the change-basis.
=> #22: Start with ZC1.5.5e code versions

1_Installation_Files (v1.5.5)/includes/modules/YOUR_TEMPLATE/additional_images.php, 1_Installation_Files (v1.5.5)/includes/modules/YOUR_TEMPLATE/main_product_image.php
=> #22: Apply PSR-2 styling

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php
=> #20: Re-factor prior to other changes

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_uninstall.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/extra_datafiles/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler_uninstall.php
... allows stores to limit access via admin profiles.
=> #33: Add a separate uninstall script

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php
Refactor to use PSR-2 styling and update the plugin "uninstall" link to
reference the now-separate uninstall module.
=> #20, #33: Refactor; update removal link

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php
... adding an admin-page registration for the uninstall module.
=> #33: Update install script

readme/image_handler_readme.html, readme/includes/css/stylesheet.css
Update the readme to reflect the IH5 changes.
=> Readme restructuring and updates

1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php
No need to occupy space with unused class!
=> #32: Don't load unused gifinfo class

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/classes/observers/ImageHandlerAdmin.php
=> #20: Capture admin IH class

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_uninstall.php
Remove the admin class-file on an uninstall action.
=> #33: Uninstall admin class file, too.

readme/image_handler_readme.html, readme/includes/css/stylesheet.css
Update the readme to change references to IH5 and identify changes in
that release.
=> Update readme for IH5

1_Installation_Files (v1.5.5)/includes/templates/YOUR_TEMPLATE/css/style_imagehover.css, readme/image_handler_readme.html
Include example settings using CSS3 media queries in the supplied .css
file.
=> #4: Disable imagehover on small devices

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, README.md, readme/image_handler_readme.html
Update the readmes and update the database-stored version to
5.0.0-beta4.
=> Update readme, version to 5.0.0-beta4

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php
Update the module to use the new form of the function call.
=> #17: Correct missing function debug-log

1_Installation_Files (v1.5.5)/includes/classes/bmz_gif_info.class.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/divavocals/zen_image-handler/52)
=> Add missing underscore to construct

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/divavocals/zen_image-handler/54)
=> Replace bracket with curly bracket

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php
#53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/divavocals/zen_image-handler/57)
=> Update $page to $ih_page

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, 1_Installation_Files (v1.5.5)/includes/classes/observers/ColorBoxObserver.php
... searching for the colorbox module within the template-override
paths.
=> #59: Correct ColorBox integration

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, readme/image_handler_readme.html
=> Update readme/version for release

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, 1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, readme/image_handler_readme.html
"Sanitize" the input to `imagepng`, keeping that quality input in the
range 0-9.
=> #64: Sanitize .png quality input prior to use

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_uninstall.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler_about.php, readme/image_handler_readme.html
... making it possible to translate those instructions!
=> #66: Separate help text for Tools->Image Handler to a language file

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php
Align indentation, remove extraneous parentheses.
=> ih_manager: Re-factor prior to change

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php
... on the check_page function call.
=> #75: Correct missing parameter

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_uninstall.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_view_config.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/classes/ImageHandlerAdmin.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/extra_datafiles/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/extra_definitions/image_handler_extra_definitions.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler_view_config.php, readme/image_handler_readme.html
... to the Image Handler's admin menu.
=> #83: Add "View Configuration" tool

1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php
Update the base IH class:
1. Add admin/storefront in-code debug configuration.
2. Don't "find" matching image names with mismatched file types.
3. Updates to use pathinfo to split the filename/extension.
=> #90, #88, #73: Don't find mismatched file types

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler.php
=> #71: Change image-header from 'size' to 'image'

1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_image_handler.php, readme/image_handler_readme.html
... recognizing that "transparent" (by itself) is also valid.
=> #101, correct check for invalid background setting

1_Installation_Files (v1.5.5)/includes/classes/observers/FualSlimboxObserver.php, readme/image_handler_readme.html
... by ensuring that the zen_lightbox function is available.  Ensures correct handling in the presence of a partially installed version of that plugin.
=> #97: Correct Fual Slimbox integration

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, 1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, 1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_image_handler.php, 1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_io.php, readme/image_handler_readme.html
Update various modules, per the referenced issue.
=> #106: Restructuring and debug

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php
=> #106, capture admin changes

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_view_config.php, 1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, 1_Installation_Files (v1.5.5)/includes/extra_configures/bmz_image_handler_conf.php, pages/configuration.md, pages/image_handler.md, pages/troubleshooting.md, readme/image_handler_readme.html
... also includes some documentation refinements.
=> #89: Remove mixed case ext

1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, 1_Installation_Files (v1.5.5)/includes/classes/observers/ImageHandlerObserver.php
... and modify the ih_image class to properly cast the requested image's width/height to integers.
=> #117-correct-large-size-constants

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/extra_datafiles/image_handler_admin_logging.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, 1_Installation_Files (v1.5.5)/includes/extra_datafiles/image_handler_logging.php, docs/image_handler/readme.html, pages/troubleshooting.md
Add the admin version of the logging "extra_datafile", updating the readmes to identify the new files.
=> #106: Correct admin debug

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/extra_definitions/image_handler_extra_definitions.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler.php, docs/image_handler/readme.html
Correct PHP Notice on already-defined ICON_IMAGE_HANDLER
=> #126-Correct-php-notice

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php, docs/image_handler/readme.html
Set flags properly for the `save` operation, remove extraneous parameter from findAdditionalImages method call and add some more debug-trace messages.
=> #130-image-additions-corrections

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php
To correct the specified debug-log.
=> #134-add-missing-cast

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, docs/image_handler/readme.html
Update the readme and the installation script to reflect the change.
=> #134-include-version-doc-changes

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php, docs/image_handler/readme.html
From what I can surmise, this applies to IH versions prior to 4.3.4.
=> #151: Correct upgrade when IH_VERSION isn't recorded

1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/image_handler_view_config.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/classes/ImageHandlerAdmin.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/ih_manager.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler.php, 1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/languages/english/image_handler_about.php
Fix for warning: Undefined array key "products_id" on line 39, on initial page load
Addition of clause for ZC158 function name change
FIx for category not being maintained on product change
The rest are html5/validation things, strict comparison checks and misc IDE inspections.
=> IH Admin pages: fixes and code tightening

1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_image_handler.php
=> Function review

1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php
No changes to functionality. All based on IDE code inspections/complaints (based on php 7.1), intended to make real code changes later easier.
Code is in production on php8 with no issues with strict checks.
I intend to do the other files (that require far less work) prior to cleaning up the use of the width/heights integers/floats etc. that are scattered about liberally but need more examination.
=> Class review

1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php, 1_Installation_Files (v1.5.5)/includes/functions/extra_functions/functions_bmz_image_handler.php, docs/image_handler/readme.html
Adding casts for calculated values, correcting #233
=> Adding casts for calculated height/width values

1_Installation_Files (v1.5.5)/YOUR_ADMIN/includes/init_includes/init_image_handler.php
=> #231: Short array syntax, removing extraneous spaces

YOUR_ADMIN/includes/init_includes/init_image_handler.php, docs/image_handler/readme.html
Note: the admin initialization script has a couple of 'refinements' as well.
=> #19: Update readme and init identifying change

YOUR_ADMIN/image_handler.php, YOUR_ADMIN/includes/classes/ImageHandlerAdmin.php, YOUR_ADMIN/includes/init_includes/init_image_handler.php, docs/image_handler/readme.html, includes/classes/bmz_image_handler.class.php, includes/functions/extra_functions/functions_bmz_image_handler.php
=> Allow webp images to be processed
